# Essential Utilities
install openssl
install wget
install ack
install tree

# Usefull tools
install tmux
install ctags
install imagemagick

# Languages
install objective-caml
install leiningen

# Stupid stuff
install cowsay
install fortune
