# Essential Utilities
brew 'openssl'
brew 'wget'
brew 'ack'
brew 'vim'
brew 'tree'

# Usefull tools
brew 'tmux'
brew 'ctags'
brew 'imagemagick'

# Languages
brew 'objective-caml'
brew 'leiningen'

# Stupid stuff
brew 'cowsay'
brew 'fortune'
