default:
	echo Hello

#######################################################################
#                          Installing Stuff                           #
#######################################################################
.PHONY:  install.zprezto

install.zprezto:
	bash scripts/install-zprezto.sh

install.vim.plugged:
	bash scripts/install-plugged.sh

#######################################################################
#                           File Operations                           #
#######################################################################
.PHONY: put.bofh put.cowsay 

put.bofh:

put.cowsay:
