- name: "HOMEBREW | Checking Homebrew installation"
  shell: command -v brew >/dev/null
  register: reg_brew_exists
  changed_when: False
  ignore_errors: yes

- name: "HOMEBREW | Copying the Homebrew installation script"
  copy: src=install-homebrew.rb dest=/tmp/ansible
  when: reg_brew_exists.rc == 1

- name: "HOMEBREW | Installing Homebrew"
  shell: ruby /tmp/ansible/install-homebrew.rb > /tmp/ansible/script.log
  when: reg_brew_exists.rc == 1